remove(getEnv): unnecessary utility
TeamAilurus/ailurus pull request #5
Opened 2022-04-19 17:17 UTC by Nciklol

2022-04-19 17:19 UTC, Kurpp commented
also you shouldnt throw errors if DISCORD_TOKEN is empty because people could name it something else!!!

2022-04-19 17:21 UTC, Nciklol commented
> also you shouldnt throw errors if DISCORD_TOKEN is empty because people could name it something else!!!

great point, we should try to avoid forcing conventions as much as possible

2022-04-19 20:22 UTC, Kurpp requested changes

2022-04-19 22:43 UTC, twisttaan commented on src/client/Client.ts
> +	public token = process.env.DISCORD_TOKEN as string;
Good idea

2022-04-19 22:43 UTC, twisttaan approved these changes

2022-04-20 00:42 UTC, Kurpp approved these changes
LGTM

2022-04-20 00:43 UTC, merged